### ISSUE TITLE
Why is not `Path("test.txt").parent.parent` a valid path?

### ISSUE THREAD

**Issue by Delgan** [jaraco/path#129]
Hello.

I love the concept of `path.py`, but this is the first time I use it and I am a bit disappointed.

While working with relative paths, I was wondering why `Path("test.txt").parent.parent` and `Path("test.txt").parent` return both `""` instead of  `"../somefolder/"` and `"."`.

My use case is very simple. The user gives me some string path where I need to create a file. So, I first need to create the folder where the file will be located.

```python
Path("test.txt").parent.makedirs_p()
```

This raises a `FileNotFoundError` because path `Path('')` does not exist.

By extension, I notice that `parent.parent` will unfortunately not return a relative path starting with `..`.

I have the feeling that we miss the opportunity for a very useful feature here.

Do you think this would make sense to implement this?

**Comment by rspeed** [comment]
You're putting in a relative path, then trying to work from it as thought it were absolute. Use `abspath` to convert it first:

```python
from path import Path
Path("test.txt").abspath().parent
```

**Comment by Delgan** [comment]
As I see it, the main use case comes from the abstraction of the path type which eases the use of the library while dealing with user inputs paths.

This would mean that one could work indifferently with absolute or relative paths.
The only thing that would change would be the display output.

Compare `print(path.parent)` to `print(path.abspath().parent.relpath())`.

The relative / absolute attribute is not intrinsic to the path, it is just a way to display it.
Suppose my working directory is `/home/user/`, then `Path('file.txt')` and `Path('/home/usr/file.txt')` represent the same file, why would their `.parent` be different?

**Comment by jaraco** [comment]
I like the proposed concept in principle. Could it be made to work in the general case? What is the parent of "test.txt" is it "test.txt/.." or simply ""? Should parent assume the current path is a directory or does it even make sense to ask for a parent of a file? I feel uneasy calculating a parent relative to a working directory implicitly.

I guess the concept of a parent of a path doesn't feel well defined to me. If we could either cite or design a definition of a parent that is intuitive and meets the expectations of the OP, I could endorse it.

**Comment by rspeed** [comment]
Perhaps something like this:

```python
>>> Path("foo/bar").parent # Currently works
Path('foo')
>>> Path("foo/bar").parent.parent
Path('.')
>>> Path("foo").parent.parent
Path('..')
>>> Path("foo").parent.parent.parent
Path('../..')
```

Preferably, this would only be implemented on `Path.parent` and not `Path.dirname`.

**Comment by Delgan** [comment]
After considering it more closely, perhaps it is a false good idea...

I looked a bit at what was being done in other implementations.

* [C++](http://en.cppreference.com/w/cpp/experimental/fs/path/parent_path)
* [Rust](http://en.cppreference.com/w/cpp/experimental/fs/path/parent_path)
* [Python](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parent)

Python's documentation explictly states that "_this is a purely lexical operation_".

This is why the equivalent of `Path("../..").parent` returns `Path("..")` in the three listed languages.

Is it the desired behavior for `path.py`? Would `Path("../../..")` seem more logical?

-----

At first I thought we could simply use an absolute path internally, but of course it is a bad idea (a relative path converted to absolute will be incorrect if initialized in a different folder).

I think my initial misunderstanding comes from the fact that some methods of a `Path()` object act on the real and "physical" path (the file on the hard drive), while others work only on the string of the path. Path "strings" and Path "files" are two different things, and we have to be careful about what the method or attribute we are using is doing.

The thing is that some properties like `.ctime` will translate a relative path automatically in order to retrieve the value, while `.parent` or `.name` will directly perform on the string. On the other hand, methods like `.dirname()` returns a result with respect to the string while most other methods are related to the pointed file.

While doing some research, I found two issues that were somehow related to what I am describing: https://github.com/jaraco/path.py/issues/26 and https://github.com/jaraco/path.py/issues/58.

My opinion on this: a property which works on the file itself will, at least implicitly, convert a relative path into an absolute path to retrieve the information it needs. This is an important context-dependent operation, and should therefore be a method rather than an attribute.

So, `ctime` would become `ctime()` and `getctime()` could be removed.
Quite conveniently, we could then have `Path("../..").dirname == Path("..")` and `Path("../..").parent() == Path("../../..")`.

Sorry to get away from the initial problem, just sharing some thoughts.

**Comment by jaraco** [comment]
It's also useful these days to reference [pathlib](https://docs.python.org/3/library/pathlib.html), which seems to have settled on a similar concept, but uses object-oriented techniques to separate a "pure" path from a "concrete" path. I prefer that concept to using the method/property distinction, as it's conceivable (likely) that pure paths will have a use for methods (as is illustrated by the pathlib API).

I've mentioned in other places the desire to align with pathlib where that doesn't compromise the [advantages path has over pathlib](https://github.com/jaraco/path.py/blob/master/README.rst#advantages).

**Comment by Nodd** [comment]
If the current path is `/`, what is `Path(toto.txt).parent.parent` ? Relative paths are harder to get right than absolute paths. Trying to play with `..` may work in some cases, but it may be harder to manage when things break, because the behaviour will be less staightforward.

**Comment by Delgan** [comment]
Hey @jaraco!

I'm not sure to understand what is "that" referring to in your question about the impact on my original use cases. For now, whenever I want to deal with the containing folder of a file, I have first to explicitly convert it to an absolute path before accessing its parent. If I forget to do so, sometimes it will work (if the file path is `folder/file.txt`), sometimes it will fail (if the file path is `file.txt`).

I have been thinking periodically to this issue since I opened it, but I still don't know what is the best way to handle this. I mean, sometimes operating on the string makes sense, other times it is much more convenient to obtain the "real" parent.

You are right that this is somehow similar to the `PurePath()` / `Path()` distinction made in `pathlib`, and I later realized that the method / attribute distinction I proposed was actually a terrible idea.

So, it looks I'm coming back to my first proposal. What about `path.dirname()` staying a lexical-only operation while `path.parent()` being equivalent to `pathlib.Path(path).resolve().parent`?

**Comment by jaraco** [comment]
> What about path.dirname() staying a lexical-only operation while path.parent() being equivalent to pathlib.Path(path).resolve().parent?

That might work. Does `resolve()` mean to resolve the path relative to the current working directory?

Why not always have `path.parent()` always return `Path(path / '..')` and leave it to the user to resolve that (or error if it represents an invalid path)?

**Comment by Delgan** [comment]
Yeah, `resolve()` would actually convert a relative to absolute path, which is a side-effect probably not expected while calling `.parent()`...

Adding `".."` to the path as you suggest is probably the best way to handle this, I considered it in the past but discarded it for a reason I can't remember now.
Note that using path like `"somefile/.."` (which would happen if we need the directory of a file path provided by the user) would often raise `NotADirectoryError` when used with functions like `os.listdir()`.

**Comment by jaraco** [comment]
> Note that using path like `"somefile/.."` would often raise `NotADirectoryError` when used with functions like `os.listdir()`.

That seems perfectly reasonable to me; if we define `parent()` as a lexical operation and there's no lexical operation to get the parent of a file, I'd expect `.parent()` of a file to cause some sort of error.

**Comment by Delgan** [comment]
> That seems perfectly reasonable to me; if we define `parent()` as a lexical operation and there's no lexical operation to get the parent of a file, I'd expect `.parent()` of a file to cause some sort of error.

Yeah, but in the end, it does not solve the initial issue, `Path("test.txt").parent().makedirs_p()` would still not work. Instead, `Path("test.txt").parent().abspath().makedirs_p()` should be used, which is very similar to the already existing solution `Path("test.txt").abspath().parent.makedirs_p()`.

Is it better to replace the current `.parent` behavior from "remove `/xyz` from this end" to "add `/..` to the end"? I don't know, at least it avoid the redundancy between `.parent` and `.dirname`, but I am not sure of which use case it solves.

My initial thoughts was about practicality.
If I receive a `Path()`, no matter if it an absolute or relative directory or file, I can get its parent and list what it contains without needing a safety call to `.abspath()`.

**Comment by jaraco** [comment]
As I revisit this issue, I realize that there's a fundamental ambiguity in `Path('something')`. You can't tell without more context whether that path refers to a file or a directory. And the meaning of "parent" is possibly different depending on the context.

In your primary use-case, you have that context. You know that `Path("test.txt")` is meant to be a filename, so `Path("test.txt").parent` should be a directory, but since it is blank, it doesn't represent a valid directory.

I do think it may be possible to achieve what you're after with something like this:

```
class Concrete(Path):
    def __new__(cls, orig, base=None):
        return super().__new__(cls, orig)

    def __init__(self, orig, base=None):
        super().__init__(orig)
        self.base = Path.getcwd() if base is None else base

    @property
    def parent(self):
        res = self.base / self / Path('..')
        return Concrete(self.base.relpathto(res), self.base)
```

The `Concrete` subclass stores the "base" - the location that makes this instance concrete... and then when computing the parent, does that relative to the base.

And at least for your use-case, this has the desired properties:

```
>>> cp = path.Concrete('test.txt')
>>> cp.parent
Concrete('.')
>>> cp.parent.parent
Concrete('..')
```

I'm worried this concept doesn't generalize well. I'm also fairly sure there are issues with other methods, as anything that invokes `self._next_class()` will have a `base` from `Path.getcwd()`.

Perhaps that can be addressed with:

```
    def _next_class(self, val):
        return self.__class__(val, base=self.base)
```

I've pushed this code to the feature/concrete-path branch. Maybe have a peek and let me know what you think.

**Comment by Delgan** [comment]
Hi @jaraco. Sorry for the late answer. I woke up this morning remembering about your comment I did not replied!

Thanks for revisiting this issue and taking the time to experiment new features.

> As I revisit this issue, I realize that there's a fundamental ambiguity in `Path('something')`. You can't tell without more context whether that path refers to a file or a directory. And the meaning of "parent" is possibly different depending on the context.

I don't understand how is the meaning of "parent" related to `something` being a file or not. Whether `something` is a file or a directory, its parent can be defined as "the directory which contains `something`". What is the ambiguity I'm missing?

However, I do agree that the implementation may require to address several concerns which are discussed in this issue but to which I have no proper solution.

I think your suggestion  to use a `Concrete()` object is a good approach. Actually, in my initial use case, I expected `Path("test.txt")` to represent the `test.txt` file on my current working directory, so I expected getting the parent folder of this file to be straightforward. In reality, `Path("test.txt")` does not represent any concrete file until it has been explicitly resolved. I guess my initial expectations was to all `Path()` objects to actually be concrete paths.

In the end, I'm not sure it worth complicating `path.py` API with a new `Concrete()` type of path, especially as you raise concerns about possible edge cases which may break unexpectedly.

**Comment by jaraco** [comment]
> I don't understand how is the meaning of "parent" related to `something` being a file or not. Whether `something` is a file or a directory, its parent can be defined as "the directory which contains `something`". What is the ambiguity I'm missing?

As I read this now, almost a year later, I don't know what I was thinking at the time, but I agree with you, there does not seem to be any ambiguity.

In #194, I've added the proposal, basically unchanged from how I drafted it at the time of this discussion. Given that I've not had a use-case for this myself and that even the OP is not confident this behavior is needed, I'm going to suggest users interested in this feature try out a copy of `Concrete` locally. If it serves a useful purpose, please feel free to revisit this issue and report its usefulness (and any issues you might have encountered)... and this project will happily host it if it serves a need.
