### ISSUE TITLE
Add standard type hints / stub files

### ISSUE THREAD

**Issue by 5j9** [jaraco/path#168]
I was working with PyCharm and noticed that it does not give useful auto-completion suggestion for this module.

```
from path import Path

file_list = Path(r'.').listdir()
file_list[0].<no useful suggestion>
```

I guess this is because of lack of type hints/stub files.
Do you have any plans for adding them?

**Comment by jaraco** [comment]
No plans but happy to accept the contribution.

**Comment by jaraco** [comment]
This issue appears to have resolved itself.

![image](https://user-images.githubusercontent.com/308610/88604975-ab648080-d046-11ea-989a-da89434d4dd2.png)

**Comment by jaraco** [comment]
Also, the package is tested under mypy now. Still I welcome enhancements.

**Comment by dmerejkowsky** [comment]
Hello @jaraco - if you want I can start working on a PR and try running mypy in `--strict` mode until everything works.

I've already done that in [a](https://github.com/tankerhq/tbump) [few](https://github.com/tankerhq/tsrc) [projects](https://github.com/tankerhq/python-cli-ui) :)

**Comment by jaraco** [comment]
I don't have a lot of experience with type hints. What experience I've had has been mixed - adding complication but little value. So I'm hesitant to accept a massive overhaul that's interleaved with the code. I'd be more inclined to accept something that's incremental or in a separate file. I'd be more inclined to accept such a PR if there's a story about what value type hints would provide or what problem it solves. Please proceed with some caution - maybe send an early draft for feedback... walk me through the thought process. Thanks.

**Comment by dmerejkowsky** [comment]
> I'd be more inclined to accept something that's incremental or in a separate file

Fair enough - it's completely understandable :)

> I'd be more inclined to accept such a PR here's a story about what value type hints would provide or what problem it solves

I'm so glad you asked! I've [written a blog post](https://dmerej.info/blog/post/giving-mypy-a-go/) about this very topic.

**Comment by dmerejkowsky** [comment]
Also, in case you want specific to path pie, here's a kind of bug that happens to me very often (and I've used path pie _a lot_ by the way:

```python
import typing
from path import Path

def read_conf() -> typing.Dict[str, str]:
    ....

def do_stuff(path: Path):
    with path:
        subprocess.run(["some", "command"])

def main() -> None:
    path = read_conf()["path"]
    do_stuff(path)
```

Today mypy alone cannot catch the bug; and that would be solved with a separate `path.pyi` distributed alongside the `path` module.
