### ISSUE TITLE
Joining a drive and path results in invalid path (windows)

### ISSUE THREAD

**Issue by char101** [jaraco/path#175]
```python
>>> Path('C:\a\test.txt').drive / 'dir'
Path('C:dir')
```

**Comment by jaraco** [comment]
I'm not sure the described behavior is a bug. `ntpath` (os.path on Windows) has the same behavior:

```
>>> ntpath.join('C:', 'dir')                                                                                                                                 
'C:dir'
```

Moreover, `C:dir` is a valid path on Windows. It means "the path 'dir' relative to the last working directory on the C drive" (Windows keeps "last working" directories for each drive).

If you think the behavior should be different, can you put together a proposal on how it should behave and why? You'll want to be careful to ensure that you support `C:dir` as a valid path.

**Comment by char101** [comment]
Thanks, I was not aware that `C:dir` is a valid path. I didn't remember the problem but maybe I was dealing with a program that does not support such path. I will close this issue since it is not a problem with `path.py`.
