### ISSUE TITLE
Tests on travis failing

### ISSUE THREAD

**Issue by jaraco** [jaraco/path#188]
With 1b5f6363692a9f0efa742ebf68c0c36e8c45227f, tests on [Travis started failing](https://travis-ci.org/github/jaraco/path/builds/687946642).

In particular, it's the [test that asserts no dependencies](https://github.com/jaraco/path/blob/4686eae1323dd39561a63b0efe345289d4c0e56e/test_path.py#L1216-L1222). I suspect the use of `python -S` is somehow breaking the system environment now that virtualenv is used instead of tox-venv.

I'm unable to replicate the behavior locally (macOS), so the issue may be isolated to Linux.

**Comment by jaraco** [comment]
On the other hand, the same code is [passing on Azure](https://dev.azure.com/jaraco/path/_build/results?buildId=643&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e), so the issue seems to be local to Travis.

**Comment by jaraco** [comment]
In [this build](https://travis-ci.org/github/jaraco/virtualenv/builds/690080014), I demonstrated that the issue is that virtualenv on Travis is old and if it's upgraded, the issue no longer occurs.

**Comment by jaraco** [comment]
@gaborbernat, you should probably be aware of [this failure](https://travis-ci.org/github/jaraco/virtualenv/builds/690083625) where a default (16.x) installation of virtualenv as found on Travis-CI will fail to run when invoking `python -S`. I was going to file an issue with virtualenv until I realized that the issue was isolated to older virtualenv versions and the workaround was to upgrade to virtualenv 20+. I encountered this issue after migrating this project off of `tox-venv`.

**Comment by gaborbernat** [comment]
Yeah, this was a known limitation of the old virtualenv.
