### ISSUE TITLE
Autogenerated documentation mis-represents "mode" argument defaults

### ISSUE THREAD

**Issue by SethMMorton** [jaraco/path#197]
In the code, the `mode` default is `0o777`. This is the number `511` in decimal. Here is what the mode default shows in the documentation:

![image](https://user-images.githubusercontent.com/1596189/94845224-3f025680-03d4-11eb-9506-dba838308fc3.png)

It just so happens that `511` (in octal) would be a valid (but odd) mode.

Since the displayed default does not have the `0o` prefix, a user unfamiliar with the requirement that the mode be given with the octal prefix to match what they would supply to the `chmod` tool might get confused and give (for example) `makedir(mode=750)` which would not do what they expect. (Source: I had a colleague do exactly that based on the representation of the default mode in the documentation).

I realize this might be more effort than it is worth, but if there was a way to force the documentation to render this in octal it might be clearer, like the Python docs to here:

![image](https://user-images.githubusercontent.com/1596189/94845590-c2bc4300-03d4-11eb-8537-0f88ad8e265d.png)

**Comment by jaraco** [comment]
I agree that would be preferable, though I don't know any way to configure automodule to present default values as octal. My guess is it would require a feature request to the [relevant project](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#module-sphinx.ext.autodoc), as I don't see anything about honoring octal literals. I'd be disinclined to accept a change that requires a second copy of the rendered docs.

**Comment by jaraco** [comment]
Looks like Sphinx has a plugin that might enable this behavior (https://github.com/sphinx-doc/sphinx/pull/8771). Would someone be willing to try that out?

**Comment by jaraco** [comment]
I tried adding the extension to the build, but the hex defaults still render as decimal.
